# .github/workflows/sync-articles.yml (VERSION 2 - MORE ROBUST)
name: Sync Articles to GitHub Pages CDN

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      # --- THIS IS THE NEW STEP ---
      - name: Install dependencies
        run: npm install csv-parse
        
      - name: Sync articles from Google Sheets
        env:
          GOOGLE_SHEETS_URL: ${{ secrets.GOOGLE_SHEETS_URL }}
        run: node sync-articles.js
        
      - name: Commit updated articles
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add articles.json index.html
          # Only commit if there are changes
          git diff --staged --quiet || git commit -m "📰 Auto-update articles from Google Sheets"
          git push
