# .github/workflows/sync-articles.yml (MORE ROBUST VERSION)
name: Sync Articles to GitHub Pages CDN

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: pip install requests
        
      # This step now has a unique ID so we can check its outcome
      - name: Run Python script to generate articles.json
        id: sync_script
        env:
          GOOGLE_SHEETS_URL: ${{ secrets.GOOGLE_SHEETS_URL }}
        run: python sync_articles.py
        
      # This step will ONLY run if the python script above was successful
      - name: Commit and Push if script succeeded and changes exist
        if: steps.sync_script.outcome == 'success'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add articles.json
          if ! git diff --staged --quiet; then
            git commit -m "📰 Auto-update articles from Google Sheets"
            git push
          else
            echo "No changes detected in articles.json."
          fi
