# .github/workflows/sync-articles.yml (FINAL PRODUCTION VERSION v2)
name: Sync Articles to GitHub Pages CDN

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
        
      - name: Run the Python sync script
        env:
          GOOGLE_SHEETS_URL: ${{ secrets.GOOGLE_SHEETS_URL }}
        run: python sync_articles.py
        
      # This is the corrected commit step
      - name: Commit and Push if Changes Exist
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # --- THIS IS THE CRITICAL FIX ---
          # Add the articles.json file to the staging area
          git add articles.json
          
          # Now, check if there are any staged changes
          if ! git diff --staged --quiet; then
            # If there are changes, commit and push them
            git commit -m "📰 Auto-update articles from Google Sheets"
            git push
          else
            # If there are no changes, do nothing
            echo "No changes to commit. articles.json is already up to date."
          fi
