name: Sync Articles to GitHub Pages CDN

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write  # Needed to commit files
  pages: write     # Needed for Pages deployment

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Sync articles from Google Sheets
        env:
          GOOGLE_SHEETS_URL: ${{ secrets.GOOGLE_SHEETS_URL }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: node sync-articles.js
        
      - name: Commit updated articles
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add articles.json index.html
          git diff --staged --quiet || git commit -m "📰 Auto-update articles $(date)"
          git push
