# .github/workflows/sync-articles.yml (PYTHON-ONLY DEBUGGING)
name: Sync Articles to GitHub Pages CDN

on:
  workflow_dispatch: # Only run manually for this test

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: pip install requests
        
      - name: Run the Python sync script
        env:
          GOOGLE_SHEETS_URL: ${{ secrets.GOOGLE_SHEETS_URL }}
        run: python sync_articles.py
